server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/work
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:com/ymr/mapper/**.xml

debug: true

logging:
  config: classpath:log/logback-spring.xml
  file:
    path: D:/log